### PR TITLE
XRT-2692: Bring 3.0 example configs up to date

### PR DESCRIPTION
**Pull request by AIM289**
I set up a test xrt branch to pull in from this examples branch and now example tests are passing on the CI: 

https://jenkins.iotechsys.com/job/XRT/job/XRT-2658-branch-test-2/

### CODE REVIEW

**Comment by BinduRao2018** [comment]
@AIM289, https://jenkins.iotechsys.com/job/XRT/job/XRT-2658-branch-test-2/6/console - example run crashes.. Also, I don't think the examples are not run in the previous builds either.

**Comment by AIM289** [comment]
> @AIM289, https://jenkins.iotechsys.com/job/XRT/job/XRT-2658-branch-test-2/6/console - example run crashes.. Also, I don't think the examples are not run in the previous builds either.

[Run 2 passed examples.](https://jenkins.iotechsys.com/job/XRT/job/XRT-2658-branch-test-2/2/). Not sure why that most recent run crashed though. Will take a look

**Comment by AIM289** [comment]
Ready for review @BinduRao2018 . Now runs all examples successfully on 3.0 

https://jenkins.iotechsys.com/job/XRT/job/XRT-2692-branch/10/

**Comment by AIM289** [comment]
Lua example fixed: https://jenkins.iotechsys.com/job/XRT/job/XRT-2692-branch/25/

Also have an xrt PR out with some scripting changes required for these examples and a required sparkplug fix: https://github.com/IOTechSystems/xrt/pull/1793

Please could you review this examples PR first, as I'll need to undo change to auth.sh in other PR once this is merged

@BinduRao2018

**Review by BinduRao2018 — APPROVED** [review]
LGTM

**Pull request merged**
