### PR TITLE
XRT-2277: Update MQTT Bridge to extend topic configuration

### PR DESCRIPTION
**Pull request by BinduRao2018**

### CODE REVIEW

**Review by SteveOss — CHANGES_REQUESTED** [review]
Most examples have retain set to true, typically retain should be false. Would only set to true if is some actual requirement to retain data published on the topic.

**Review by SteveOss — CHANGES_REQUESTED** [review]
Think example config needs updating

**Comment by BinduRao2018** [comment]
@SteveOss, could you point me to the file that needs updating?

**Review by SteveOss — APPROVED** [review]
LGTM: Ignore previous duff comment :)

**Pull request merged**
