### PR TITLE
XRT-1094: Update configs to use MQTTBridge component instead of MQTTExporter

### PR DESCRIPTION
**Pull request by BinduRao2018**

### CODE REVIEW

**Review by SteveOss — CHANGES_REQUESTED** [review]
We havn't cut a 1.2 branch yet, should this not be going onto master ?

**Comment by SteveOss** [comment]
@BinduRao2018 Ignore previous comment, realised is examples repo not xrt !

**Review by SteveOss — CHANGES_REQUESTED** [review]
In a config file for virtaul device service we have:

"Logger":"logger_debug",

Think should just be called "logger" as is the only one.

**Comment by BinduRao2018** [comment]
In this example, we are using two instances of logger  - 1. 'logger' where the log level is set to 'warn' and 2. logger_debug set to 'debug'. Virtual device service uses logger_debug, whereas the rest of the components use 'logger' instance.

**Review by SteveOss — APPROVED** [review]
LGTM

**Pull request merged**
