### PR TITLE
XRT-633-branch-2

### PR DESCRIPTION
**Pull request by mcsjuhasz**
Added missing env.sh

### CODE REVIEW

**Comment by LukeKerr** [comment]
@mcsjuhasz PR should be set up to merge with master instead of v1.1-branch for lastest changes.

**Review by SteveOss — COMMENTED** [review]
Quick comment, which isn't the env.sh in the XRT install enough ?

**Comment by mcsjuhasz** [comment]
No, the Makefile requires the ${IOT_DIR}, ${XRT_DIR} environment variables to compile the app-component shared library. These are the ones that the envs.sh sets up. Would be actually a great concept to just use the one in the XRT install. Will have a look how to generalize it and will adjust as well note for future examples.

**Comment by LukeKerr** [comment]
Could IOT_DIR and XRT_DIR not be set in the makefile instead, since you only need the paths to compile, after you would only need to update LD_LIBRARY_PATH to include the new component, like the bus example?

https://github.com/IOTechSystems/xrt/tree/v1.1-branch/src/c/examples/bus
https://github.com/IOTechSystems/xrt/blob/v1.1-branch/src/c/examples/Makefile.defs

**Comment by SteveOss** [comment]
Really the xrt env.sh should set up everything required both for deployment and development (this is what we put in our
documentation). So we should be changing this if required.

**Comment by mcsjuhasz** [comment]
Makes sense, will do the modifications on a new branch and update the documentation accordingly. Thanks.

**Pull request merged**
